import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import CrispChat from "@/components/app/CrispChat";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'], fallback: ['system-ui', 'arial'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <Toaster/>
            <CrispChat />
                {children}
            </body>
        </html>
    )
}
